trigger:
- t2d2ci

extends:
  template: azure-pipeline-variabale.yml

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '17.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install and build'
- script: |
    npm t
  displayName: 'Run terraform test'