trigger:
- t2d2ci

pool:
  vmImage: 'ubuntu-latest'

parameters:
- name: ARM_CLIENT_SECRET # name of the parameter; required
  type: string # data type of the parameter; required
  default: ${{ ARM_CLIENT_SECRET }}

- name : ARM_SUBSCRIPTION_ID
  type: string
  default: ${{ ARM_SUBSCRIPTION_ID }}

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '17.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install and build'
- script: |
    npm t
  displayName: 'Run terraform test'